/*   SQL COMMAND FOR DATABASE */
CREATE TABLE user (
    id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    phone VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE createorder (
    email VARCHAR(50) PRIMARY KEY NOT NULL,
    Web_Developper VARCHAR(50) NOT NULL,
    Detail VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE payment (
    email VARCHAR(50) PRIMARY KEY NOT NULL,
    payment_method VARCHAR(10) NOT NULL,
    bank VARCHAR(10) NOT NULL,
    bank_number VARCHAR(13) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


